---
apiVersion: 1

deleteDatasources:

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  uid: prometheus1
  url: http://prometheus:9090
  isDefault: true
  version: 1
  editable: true
- name: Loki
  type: loki
  access: proxy
  orgId: 1
  uid: loki1
  url: http://loki:4100
  isDefault: false
  version: 1
  editable: true
- name: InfluxDB
  type: influxdb
  access: proxy
  orgId: 1
  uid: influxdb1
  url: http://influxdb:8086
  isDefault: false
  version: 1
  editable: true
