version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.4.1
    ports:
      - "9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092
      KAFKA_LISTENERS: INSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  fluentd:
    image: localhost:5000/my-fluentd:latest
    ports:
      - "5514:5514/tcp"
      - "5514:5514/udp"
      - "24224:24224"
      - "24220:24220"
      - "9880:9880"
    depends_on:
      - kafka
    environment:
      - FLUENTD_CONF=fluentd.conf
    volumes:
      - ./fluentd/conf:/fluentd/etc
