version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
  kafka:
    image: confluentinc/cp-kafka:5.5.0
    ports:
      - "9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092
      KAFKA_LISTENERS: INSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      # Needed for kafka-topic-ui
      KAFKA_CONSUMER_REQUEST_TIMEOUT_MS: 30000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-manager:
    image: kafkamanager/kafka-manager:3.0.0.4
    ports:
      - "9000:9000"
    depends_on:
      - zookeeper
      - kafka
    environment:
      ZK_HOSTS: zookeeper:2181
      KAFKA_MANAGER_AUTH_ENABLED: 1
      KAFKA_MANAGER_USERNAME: admin
      KAFKA_MANAGER_PASSWORD: admin
  kafka-schema-registry:
    image: confluentinc/cp-schema-registry:5.5.0
    ports:
      - "8081:8081"
    depends_on:
      - zookeeper
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
      SCHEMA_REGISTRY_LISTENERS: ":8081"
      SCHEMA_REGISTRY_DEBUG: 1
  kafka-rest:
    image: confluentinc/cp-kafka-rest:5.5.0
    ports:
      - "8082:8082"
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_HOST_NAME: kafka-rest
      KAFKA_REST_LISTENERS: ":8082"
      KAFKA_REST_SCHEMA_REGISTRY_URL: kafka-schema-registry:8081
  kafka-topic-ui:
    image: landoop/kafka-topics-ui:0.9.4
    ports:
      - "8000:8000"
    depends_on:
      - kafka-rest
    environment:
      KAFKA_REST_PROXY_URL: kafka-rest:8082
  fluentd:
    image: localhost:5000/my-fluentd:latest
    ports:
      - "5514:5514/tcp"
      - "5514:5514/udp"
      - "24224:24224"
      - "24220:24220"
      - "9880:9880"
    depends_on:
      - kafka
    environment:
      - FLUENTD_CONF=fluentd.conf
    volumes:
      - ./fluentd/conf:/fluentd/etc
