version: "3.7"
services:
  prometheus:
    image: prom/prometheus:v2.17.2
    ports:
      - 9090:9090
    networks:
      - monitoring-in
      - monitoring-out
      - kafka-in
    volumes:
      - ./prometheus/conf:/etc/prometheus
      - prometheus-data:/prometheus
  loki:
    image: grafana/loki:master-b652f0a
    command: -config.file=/etc/loki/loki-config.yaml
    restart: on-failure
    ports:
      - "3100:3100"
    networks:
      - monitoring-in
      - monitoring-out
    volumes:
      - ./loki/conf:/etc/loki
  promtail:
    image: grafana/promtail:master-b652f0a
    command: -config.file=/etc/promtail/promtail-config.yaml
    ports:
      - "9080:9080"
    networks:
      - monitoring-in
      - monitoring-out
    volumes:
      - ./promtail/conf:/etc/promtail
      - promtail-log:/var/log
  grafana:
    build:
      context: ./grafana/images/dev
      args:
        GRAFANA_VERSION: 6.7.3
    ports:
      - "3000:3000"
    networks:
      - monitoring-in
      - monitoring-out
    environment:
      GF_INSTALL_IMAGE_RENDERER_PLUGIN: "false"
      # do not forget the comma at end of lines
      GF_INSTALL_PLUGINS: >-
        grafana-clock-panel,
        grafana-simple-json-datasource
    volumes:
      - ./grafana/conf:/etc/grafana
      - grafana-data:/var/lib/grafana
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "http://loki:3100/loki/api/v1/push"
    #     loki-retries: 5
    #     loki-batch-size: 400
networks:
  monitoring-in:
    name: monitoring-in
    driver: bridge
  monitoring-out:
    name: monitoring-out
    driver: overlay
  kafka-in:
    external: true
volumes:
  prometheus-data:
  grafana-data:
  promtail-log:
