version: "3.7"
services:
  prometheus:
    image: prom/prometheus:v2.17.2
    ports:
      - 9090:9090
    networks:
      - monitoring-in
      - monitoring-out
      - kafka-in
    volumes:
      - ./prometheus/conf:/etc/prometheus
      - prometheus-data:/prometheus
  grafana:
    build: ./grafana/images/dev
    ports:
      - "3000:3000"
    networks:
      - monitoring-in
      - monitoring-out
    environment:
      GRAFANA_VERSION: 6.7.3
      GF_INSTALL_IMAGE_RENDERER_PLUGIN: "false"
      # do not forget the comma at end of lines
      GF_INSTALL_PLUGINS: >-
        grafana-clock-panel,
        grafana-simple-json-datasource
    volumes:
      - ./grafana/conf:/etc/grafana
      - grafana-data:/var/lib/grafana
networks:
  monitoring-in:
    name: monitoring-in
    driver: bridge
  monitoring-out:
    name: monitoring-out
    driver: overlay
  kafka-in:
    external: true
volumes:
  prometheus-data:
  grafana-data:
