version: "3.7"
services:
  prometheus:
    image: prom/prometheus:v2.17.2
    restart: always
    ports:
      - "9090:9090"
    networks:
      - monitoring-in
      - monitoring-out
      - kafka-in
      - fluentd-in
    volumes:
      - ./prometheus/conf:/etc/prometheus:ro
      - prometheus-data:/prometheus
  alertmanager:
    image: prom/alertmanager:v0.20.0
    restart: always
    ports:
      - "9093:9093"
    networks:
      - monitoring-in
      - monitoring-out
    volumes:
      - ./alertmanager/conf:/etc/alertmanager:ro
      - alertmanager-data:/alertmanager
  loki:
    image: grafana/loki:master-b652f0a
    command: -config.file=/etc/loki/loki-config.yaml
    restart: always
    ports:
      - "4100:4100"
    networks:
      - monitoring-in
      - monitoring-out
    volumes:
      - ./loki/conf:/etc/loki:ro
  promtail:
    image: grafana/promtail:master-b652f0a
    command: -config.file=/etc/promtail/promtail-config.yaml
    restart: always
    ports:
      - "9080:9080"
    depends_on:
      - loki
    networks:
      - monitoring-in
      - monitoring-out
    volumes:
      - ./promtail/conf:/etc/promtail:ro
      - promtail-log:/var/log
  influxdb:
    image: influxdb:1.8
    command: -config /etc/influxdb/influxdb.conf
    restart: always
    expose:
      - "8083"
      - "8086"
    networks:
      - monitoring-in
    volumes:
      - ./influxdb/conf:/etc/influxdb:ro
      - influxdb-data:/var/lib/influxd
  telegraf:
    image: telegraf:1.12
    command: -config /etc/telegraf/telegraf.conf
    restart: always
    ports:
      - "8125:8125/udp"
    networks:
      - monitoring-in
      - monitoring-out
    volumes:
      - ./telegraf/conf:/etc/telegraf:ro
      - /var/run/docker.sock:/var/run/docker.sock
  grafana:
    build:
      context: ./grafana/images/dev
      args:
        GRAFANA_VERSION: 6.7.3
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - prometheus
      - loki
      - telegraf
    networks:
      - monitoring-in
      - monitoring-out
      - kafka-in
    environment:
      GF_SERVER_HTTP_PORT: 4000
      GF_INSTALL_IMAGE_RENDERER_PLUGIN: "false"
      # do not forget the comma at end of lines
      GF_INSTALL_PLUGINS: >-
        grafana-clock-panel,
        grafana-simple-json-datasource,
        grafana-piechart-panel
    volumes:
      - ./grafana/conf:/etc/grafana:ro
      - grafana-data:/var/lib/grafana
networks:
  monitoring-in:
    name: monitoring-in
    driver: bridge
  monitoring-out:
    name: monitoring-out
    driver: overlay
  kafka-in:
    external: true
  fluentd-in:
    external: true
volumes:
  prometheus-data:
  alertmanager-data:
  grafana-data:
  influxdb-data:
  promtail-log:
