---
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'external-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'kafka-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['kafka-exporter:9308']
  - job_name: 'grafana'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['grafana:3000']
  - job_name: 'loki'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['loki:3100']
  - job_name: 'promtail'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['promtail:9080']
